### PR TITLE
STRUCT and ARRAY types are deprecated. 

### PR DESCRIPTION
**Pull request by mteufel**
STRUCT and ARRAY types are deprecated. Migration to java.sql.Struct and java.sql.Array-Types.
(This is my very first try to contribute  ;-)   )

### CODE REVIEW

**Comment by trisberg** [comment]
Thanks for the contribution, wasn't aware of these deprecations. What Java version and JDBC driver version did you compile this with?

**Comment by mteufel** [comment]
I am working with JDK 1.8.0_45 and Oracle JDBC Driver Version 12.1.0.2 actually.
The classes are deprecated since 12.1 as you can see here https://docs.oracle.com/database/121/JAJDB/deprecated-list.html

**Comment by trisberg** [comment]
Maybe it is time to move this project to more recent versions. We are currently supporting Java 6, Spring Framework 3.0 and Oracle 10g R2 drivers (10.2.0.2 or later). I would prefer to do that in a major version update though, so we would have to go to 2.0.0 since this update could break existing apps.

Making these version changes would mean AFAIK that anyone wanting to use this new version would have to use the 12.1 driver and run their app server on JDK 8. Not sure if this is to steep of a requirement. Any thoughts on this?

**Comment by trisberg** [comment]
Hi, I'm looking at merging this into the new 2.0.x branch - have you signed a contributor agreement?

See -- https://github.com/spring-projects/spring-data-jdbc-ext#contributing

**Comment by mteufel** [comment]
Yes, I have signed the contributor agreement. Starting a new 2.0 branch is a good idea. One of the main principles of Spring itself is, as far as I remember, to be backwards compatible as much as possible. What is your plan with this 2.0 stream? I would recommend to continue the main work in the 1.x stream and merge new features and bugfixes into the new 2.0 version from time to time. Thanks for taking my contribution serious.

**Comment by trisberg** [comment]
Thanks.

Merged into 2.0.x branch via commit f2df9500254a3feb94bf69e9e6db1dd6744ce332

**Pull request closed without merging**
