### PR TITLE
AbstractSQLQuery#listResults support

### PR DESCRIPTION
**Pull request by killergti**
It would be nice to have an ability to query the SearchResults.

### CODE REVIEW

**Comment by trisberg** [comment]
Looking at adding this for the next 1.2.0 release. Have you signed the contributor agreement? https://support.springsource.com/spring_committer_signup

**Comment by trisberg** [comment]
Merged via commit/510c21450466d61150ebe41e192cf497ec01cb66

Thanks for the contribution

**Comment by killergti** [comment]
Yes, I've signed the agreement.

**Comment by trisberg** [comment]
Thanks, this is now in the latest 1.2.0 release.

**Pull request closed without merging**
